<?php
$_helper = $this->helper('Magento\Catalog\Helper\Output');
$_product = $block->getProduct();

 $_attributeValue = $_helper->productAttribute($_product, $_product->getGenuineRating(), "genuine_rating");
 $attr = $_product->getResource()->getAttribute('genuine_rating');
 if ($attr->usesSource()) {
   $genuineRating=0;
   $genuineRating = $attr->getSource()->getOptionText($_attributeValue);
   $GenuineRatingWidth = $genuineRating*20;
  }


$_attributeValue = $_helper->productAttribute($_product, $_product->getPerformanceRating(), "performance_rating");
 $attr = $_product->getResource()->getAttribute('performance_rating');
 if ($attr->usesSource()) {
     $perText=0;
     $perText = $attr->getSource()->getOptionText($_attributeValue);
     $PerformanceRatingWidth=$perText*20;
     
 }
 
 
 $_attributeValue = $_helper->productAttribute($_product, $_product->getQualityRating(), "quality_rating");
 $attr = $_product->getResource()->getAttribute('quality_rating');
 if ($attr->usesSource()) {
   $qutText=0;
  $qutText = $attr->getSource()->getOptionText($_attributeValue);
  $QualityRatingWidth=$qutText*20;
   
 }
 
 
 $_attributeValue = $_helper->productAttribute($_product, $_product->getCostEffectivnessRating(), "cost_effectivness_rating");
 $attr = $_product->getResource()->getAttribute('cost_effectivness_rating');
 if ($attr->usesSource()) {
    $costText=0;
    $costText = $attr->getSource()->getOptionText($_attributeValue);
    $CostEffectivenessRatingWidth=$costText*20;
 }

$avg_auto_rating = ($genuineRating + $perText + $qutText + $costText)/4;

$avg_auto_rating = number_format((float)$avg_auto_rating, 1, '.', ''); 
                                    
$_items = $block->getReviewsCollection()->getItems();
$format = $block->getDateFormat() ? : \IntlDateFormatter::SHORT;
?>
<?php if (count($_items)): ?>

    <?php
    $itemsReview = array();
    foreach ($_items as $_review) {
        if (count($_review->getRatingVotes())) {
            foreach ($_review->getRatingVotes() as $_vote) {
                $ratingArray[$block->escapeHtml($_vote->getRatingCode())] = $_vote->getPercent();
            }
        }

        $itemsReview[] = $ratingArray;
    }
    ?>
    <?php //print_r($itemsReview); ?>

    <?php
    foreach ($itemsReview as $revitem) {

        if (count($_review->getRatingVotes())) {
            $title = array();
            if (empty($arraytotal)) {
                $arraytotal = array();
            }

            $i = 0;
            $countReviewAttribute = count($revitem);
            foreach ($revitem as $key => $value) {
                $title[] = $key;
                if (empty($arraytotal[$i])) {
                    $arraytotal[$i] = 0;
                    $i++;
                }
            }
            foreach ($revitem as $key => $value) {

                $arraytotal[array_search($key, $title)]+=$value;
            }
        }
    }

    $revieCount = count($itemsReview);
    $countReviewAttribute;


    $totalRating = array_sum($arraytotal);
    $avgRating = $totalRating / ($revieCount * $countReviewAttribute * 20);
    ?>


    <div class="product data items">
        <!--progress bar -->

        <div class="data item title  active " style="float:left" aria-labeledby="tab-label-additional-title" id="tab-label-additional">
                          <!--  <h4><strong> <a class="data switch"
                                tabindex="-1"
                                style="color:#000;"
                              
                               id="tab-label-additional-title">
                                More Information                    </a></strong></h4> -->
            <a class="data switch" tabindex="-1" data-toggle="switch" href="#additional" id="tab-label-additional-title"> Rating &amp; Review  </a>
        </div>
        <div class=" row " style="    margin: 0 0 20px 0;">
            <div class="data item content"  data-role="content" style="float:left;    padding: 15px;
                 border: 1px solid #eee; margin:0;    width: 100%;">

                <div class="row" style=" background-color: #fff; padding: 10px; border: 1px solid #eee; margin: 0px;
                     ">
                    <div class="col-md-8 col-sm-8 col-xs-8 col-lg-8">
                        <div class="row">
                            <div class="col-md-3 col-sm-3 col-xs-3 col-lg-3">

                              <!--   <svg style="" height="100" width="100">

                                <circle cx="50" cy="50" r="40" stroke="#3C3636" stroke-width="1" fill="rgb(229,229,229)"></circle>
                                <text x="15" y="78" font-family="Verdana" font-size="80" fill="rgb(255,150,45)"> ★ </text>
                                <text x="42" y="58" font-family="Verdana" font-size="15" fill="#fff"> <?php echo $avgRating; ?> </text>
                                </svg> -->

                                <div id="circle">
                                    <div class="star">★</div>
                                    <div class="star-text"><?php echo number_format((float)$avgRating, 1, '.', ''); ?> </div>
                                </div>

                            </div>  

                            <div class="col-md-7 col-sm-7 col-xs-7 col-lg-7" style=" "> 
    <?php for ($j = 0; $j < $countReviewAttribute; $j++) { ?>
                                    <h6 style=" float: left;font-size: 16px;margin: -2px 0px 0 0px;"><?php echo $title[$j]; ?></h6>
                                    <div class="progress" style=" height: 15px; float:right;">
                                        <div class="progress-bar" role="progressbar" aria-valuenow="70"
                                             aria-valuemin="0" aria-valuemax="100" style="width:<?php /* @escapeNotVerified */ echo ceil($arraytotal[$j] / $revieCount); ?>%">
                                            <span class="sr-only">70% Complete</span>
                                        </div> 
                                    </div> 
        <?php if ($j < $countReviewAttribute - 1): ?>
                                        <div style="clear:both"></div>  
        <?php endif; ?>
                                <?php } ?>  

                            </div>
                            <div class="col-md-2 col-sm-2 col-xs-2 col-lg-2" style="padding-top: 70px;
                                 "> 
                          <a href="#allreviewcustom" ><button class="btn btn-success all-review-list" style=" color: #fff;margin: -10px 0 0 0;" type="button">View All</button></a>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-4 col-sm-4 col-xs-4 col-lg-4" id="writereview" >
                        <h4  style="font-size: 17px; margin: 0 0 3px 0">Have you used this product ?</h4> 
                        <h3 style=" margin:0 0 5px 0;font-size: 19px ;" ><strong>Rating</strong></h3>  
                        <div class="rating-summary item" itemprop="reviewRating" itemscope="" itemtype="http://schema.org/Rating" style=" margin:0 0 5px 0;">

                            <div class="rating-result"  title="100%">

                                <meta itemprop="worstRating" content = "1"/>
                                <meta itemprop="bestRating" content = "100"/>
                                <span style="width:<?php echo $avgRating * 20; ?>%">
                                    <span itemprop="ratingValue">100%</span>
                                </span>
                            </div>

                        </div>

                        <a href="#rating-form"> <button class="btn btn-warning" id="write-review" style="color:#fff; border:none;" type="button">Write a Review</button></a>
                    </div> 
                </div>
            </div> 
        </div>  
                <!--rating bar end-->  

                <!--over all-->

                <div class="data item title  active " style="float:left" aria-labeledby="tab-label-additional-title" id="tab-label-additional">
                                 <!--  <h4><strong> <a class="data switch"
                                       tabindex="-1"
                                       style="color:#000;"
                                     
                                      id="tab-label-additional-title">
                                       More Information                    </a></strong></h4> -->
                    <a class="data switch" tabindex="-1" data-toggle="switch" href="#additional" id="tab-label-additional-title"> Autokart Rating </a>
                </div>
                <div class=" row " style="  margin: 0 0 20px 0;">
                    <div class="data item content"  data-role="content" style="float:left;    padding: 15px;
                         border: 1px solid #eee; margin:0;    width: 100%;">

                        <div class="row overall" style="
                             ">
                            <div class="col-md-4 col-sm-4 col-xs-4 col-lg-4">
                                <!-- <svg  height="95" width="100">

                                <circle cx="50" cy="50" r="40" stroke="black" stroke-width="1"  fill="rgb(239,239,239)" > </circle>
                                <text x="30" y="58" font-family="Verdana" font-size="20" fill="#000"> <?php echo $avgRating; ?>/5 </text>
                                </svg> -->
                                 <div id="circle">
                                     <div style=" margin: -4px 0 0 0;font-size: 32px;">
                                    <?php echo $avg_auto_rating; ?>
                                </div>
                                </div>
                                <div class=""><h4><strong>Overall</strong></h4></div>
                            </div>
                            <div class="col-md-4 col-sm-4 col-xs-4 col-lg-4" style="margin-top:10px;">
   
   
   <!--  rating auto  genuine_rating  -->
                                    <div class="rating-summary item" itemprop="reviewRating" itemscope="" itemtype="http://schema.org/Rating">
                                        <span class="label rating-label"><span>
                            <?php echo  $_attributeLabel = $_product->getResource()->getAttribute("genuine_rating")->getFrontendLabel(); ?>
                                        </span></span>
                                        <div class="rating-result"  style="float:right" title="<?php //echo ceil($arraytotal[$j] / $revieCount); ?>%">

                                            <meta itemprop="worstRating" content = "1"/>
                                            <meta itemprop="bestRating" content = "100"/>
                                            <span style="width: <?php echo $GenuineRatingWidth ?>%">
                                                <span itemprop="ratingValue"><?php /* @escapeNotVerified */ echo $GenuineRatingWidth ?>%</span>
                                            </span>
                                        </div>

                                    </div>

    <!--  end rating auto  -->
    
     <!--  rating auto  performance_rating  -->
                                    <div class="rating-summary item" itemprop="reviewRating" itemscope="" itemtype="http://schema.org/Rating">
                                        <span class="label rating-label"><span>
                            <?php echo  $_attributeLabel = $_product->getResource()->getAttribute("performance_rating")->getFrontendLabel(); ?>
                                        </span></span>
                                        <div class="rating-result"  style="float:right" title="<?php //echo ceil($arraytotal[$j] / $revieCount); ?>%">

                                            <meta itemprop="worstRating" content = "1"/>
                                            <meta itemprop="bestRating" content = "100"/>
                                            <span style="width: <?php echo $PerformanceRatingWidth ?>%">
                                                <span itemprop="ratingValue"><?php /* @escapeNotVerified */ echo $GenuineRatingWidth ?>%</span>
                                            </span>
                                        </div>

                                    </div>

    <!--  end rating auto  -->
    
     <!--  rating auto  quality_rating   -->
                                    <div class="rating-summary item" itemprop="reviewRating" itemscope="" itemtype="http://schema.org/Rating">
                                        <span class="label rating-label"><span>
                            <?php echo  $_attributeLabel = $_product->getResource()->getAttribute("quality_rating")->getFrontendLabel(); ?>
                                        </span></span>
                                        <div class="rating-result"  style="float:right" title="<?php //echo ceil($arraytotal[$j] / $revieCount); ?>%">

                                            <meta itemprop="worstRating" content = "1"/>
                                            <meta itemprop="bestRating" content = "100"/>
                                            <span style="width: <?php echo $QualityRatingWidth ?>%">
                                                <span itemprop="ratingValue"><?php /* @escapeNotVerified */ echo $GenuineRatingWidth ?>%</span>
                                            </span>
                                        </div>

                                    </div>

    <!--  end rating auto  -->
    
     <!--  rating auto  cost_effectivness_rating  -->
                                    <div class="rating-summary item" itemprop="reviewRating" itemscope="" itemtype="http://schema.org/Rating">
                                        <span class="label rating-label"><span>
                            <?php echo  $_attributeLabel = $_product->getResource()->getAttribute("cost_effectivness_rating")->getFrontendLabel(); ?>
                                        </span></span>
                                        <div class="rating-result"  style="float:right" title="<?php //echo ceil($arraytotal[$j] / $revieCount); ?>%">

                                            <meta itemprop="worstRating" content = "1"/>
                                            <meta itemprop="bestRating" content = "100"/>
                                            <span style="width: <?php echo 
                                            $CostEffectivenessRatingWidth ?>%">
                                                <span itemprop="ratingValue"><?php /* @escapeNotVerified */ echo $GenuineRatingWidth ?>%</span>
                                            </span>
                                        </div>

                                    </div>

    <!--  end rating auto  -->

                            </div>

                            <div class="col-md-2 col-sm-2 col-xs-2 col-lg-2">
                            </div>  
                            <!-- <div class="row">

                                <div class="col-md-6 col-sm-6 col-xs-6 col-lg-6 col-md-offset-4 col-lg-offset-4 col-xs-offset-4 col-sm-offset-4 text-center" >
                                    <h4 class="" style="margin: 0; float: left;">Was this review helpful</h4>  
                                    <button class="btn .btn-default" type="button" style="margin-top: -5px;float: left;width: 75px; margin-left: 15px;">Yes</button> 
                                    <div id="talkbubble">6</div>
                                </div>

                            </div> -->

                        </div>

                    </div>                

                    <!--end over all-->
                </div>


              

    </div>
              
                <!-- review list-->
                <div  id="allreviewcustom" class=" review-list-custom" >
                    <div class="block review-list" id="customer-reviews" style=" 
                     margin:0px;">
                        <div class="block-title">
                            <strong><?php /* @escapeNotVerified */ echo __('Customer Reviews') ?></strong>
                        </div>
                        <div class="block-content">
                            <div class="toolbar review-toolbar">
    <?php echo $block->getChildHtml('toolbar') ?>
                            </div>
                            <ol class="items review-items">
                                <?php foreach ($_items as $_review): ?>

                                    <li class="item review-item" itemscope itemprop="review" itemtype="http://schema.org/Review">
                                        <div class="review-title" itemprop="name"><?php echo $block->escapeHtml($_review->getTitle()) ?>

                                        </div>
        <?php if (count($_review->getRatingVotes())): ?>
                                            <div class="review-ratings">
            <?php foreach ($_review->getRatingVotes() as $_vote): ?>
                                                    <div class="rating-summary item" itemprop="reviewRating" itemscope itemtype="http://schema.org/Rating">
                                                        <span class="label rating-label"><span><?php echo $block->escapeHtml($_vote->getRatingCode()) ?></span></span>
                                                        <div class="rating-result" title="<?php /* @escapeNotVerified */ echo $_vote->getPercent() ?>%">
                                                            <meta itemprop="worstRating" content = "1"/>
                                                            <meta itemprop="bestRating" content = "100"/>
                                                            <span style="width:<?php /* @escapeNotVerified */ echo $_vote->getPercent() ?>%">
                                                                <span itemprop="ratingValue"><?php /* @escapeNotVerified */ echo $_vote->getPercent() ?>%</span>
                                                            </span>
                                                        </div>
                                                    </div>
            <?php endforeach; ?>
                                            </div>
        <?php endif; ?>
                                        <div class="review-content" itemprop="description">
                                            <?php echo nl2br($block->escapeHtml($_review->getDetail())) ?>
                                        </div>
                                        <div class="review-details">
                                            <p class="review-author">
                                                <span class="review-details-label"><?php /* @escapeNotVerified */ echo __('Review by') ?></span>
                                                <strong class="review-details-value" itemprop="author"><?php echo $block->escapeHtml($_review->getNickname()) ?></strong>
                                            </p>
                                            <p class="review-date">
                                                <span class="review-details-label"><?php /* @escapeNotVerified */ echo __('Posted on') ?></span>
                                                <time class="review-details-value" itemprop="datePublished" datetime="<?php /* @escapeNotVerified */ echo $block->formatDate($_review->getCreatedAt(), $format) ?>"><?php /* @escapeNotVerified */ echo $block->formatDate($_review->getCreatedAt(), $format) ?></time>
                                            </p>
                                        </div>
                                    </li>
    <?php endforeach; ?>
                            </ol>
                            <div class="toolbar review-toolbar">
                                <?php echo $block->getChildHtml('toolbar') ?>
                            </div>
                        </div>
                    </div>
                            <?php endif; ?>

                <script type="text/javascript">
                    require([
                        'jquery'
                    ], function (jQuery) {
                        jQuery('.review-list-custom').css('display', 'none');
                        jQuery('body').on('click', '.all-review-list', function () {
                            jQuery('.review-list-custom').toggle();
                        });
                        if(<?php echo count($_items)?>){
                        jQuery('.formRating').css('display','none');
                        }else {
                         jQuery('.formRating').css('display','block');
                        }
                        
                    });
                </script>

                <style>

                   #circle {
                   text-align: center;
    border: 1px solid #3C3636;
    width: 100px;
    height: 100px;
   -moz-border-radius: 50px;
    -webkit-border-radius: 50px;
    border-radius: 50px;
    padding-top: 30px;
    font-size: 20px;
}

.star {    margin: 0;
    color: rgb(255,150,45);
    font-size: 115px;
    margin-top: -69px;
    margin-left: -2px;}
.star-text {
color: #fff;
    left: 53px;
    margin: 0px;
    position: absolute;
    top: 37px;
    text-align: center;
}

                    #writereview {
                    
                        margin: 10px -5px 0 5px;
                        /* margin-left: 5px; */
                        /* padding-top: 70px; */
                        border-left: 1px solid;
                        /* margin-top: 15px; */
                    }
                    #writeview > h4 {
                        font-size: 17px !important;
                        margin: 0 0 3px 0 !important;
                    }
                    #writeview > h3 {
                        margin:0 0 5px 0 !important;
                        font-size: 19px !important;
                    }
                    #writeview #rating-summary {margin: 0 0 5px 0 !important;}

                    .overall {padding: 10px;  margin: 20px 0 0 0; border: 1px solid #eee;}
                    .overall h4{ margin: 0px 0 0 15px;}


                    .progress {
                        margin-bottom: 10px;     width: 175px; }
                    /*.rating-summary .rating-result:before {
                        left: 0;
                        position: absolute;
                        top: 0;
                        width: 100%;
                        z-index: 1;
                        -webkit-font-smoothing: antialiased;
                        color: #c3c5c9;
                        font-family: 'porto-icons';
                        font-size: 40px;
                        height: 40px;
                        letter-spacing: 2px;
                        line-height: 40px;
                        content: '\f844' '\f844' '\f844' '\f844' '\f844';
                        display: block;
                        font-style: normal;
                        font-weight: normal;
                        speak: none;
                    }
                    
                    .rating-summary .rating-result  > span:before {
                        position: relative;
                        z-index: 2;
                        -webkit-font-smoothing: antialiased;
                        color: #ffc600;
                        font-family: 'porto-icons';
                        font-size: 40px;
                        height: 40px;
                        letter-spacing: 2px;
                        line-height: 40px;
                        content: '\f844' '\f844' '\f844' '\f844' '\f844';
                        display: block;
                        font-style: normal;
                        font-weight: normal;
                        speak: none;
                    }*/

                    /*.rating-summary .rating-result {
                        display: block;
                        width: 195px;
                    }*/

                    #talkbubble {
                        float: left;margin-left: 20px; font-size: 20px;
                        margin-top: -7px; 
                        width: 50px;
                        height: 33px;
                        background: #FFFDFD;
                        position: relative;
                        -moz-border-radius: 10px;
                        -webkit-border-radius: 10px;
                        border-radius: 6px;
                    }

                    #talkbubble:before {
                        content: "";
                        position: absolute;
                        right: 97%;
                        top: 3px;
                        width: 0;
                        height: 0;
                        border-top: 13px solid rgba(33, 29, 29, 0);
                        border-right: 16px solid #FBFBFB;
                        border-bottom: 15px solid transparent;
                    }

                    .review-list-custom {
                       /* background-color: rgb(227,227,227); */
                        margin: 20px 0 0 0;
                        padding: 20px;
                        border: 1px solid #eee;
                    }

                    @media (min-width: 640px)
                    .review-item {
                        padding: 0 0; 
                    }

                </style>
