<?php if ($block->isEnabled()): ?>
    <div class="actions-toolbar social-btn twitter-login">
        <div class="primary">
            <button class="action" id="btn_twitter_login" type="button">
                <span>
                    <span><?php echo __('Twitter Sign In') ?></span>
                </span>
            </button>
        </div>
    </div>
    <script>
        require(['mageplaza/sociallogin'], function (SocialLoginPopup) {
            $('btn_twitter_login').observe('click', function () {
                var twPopup = new SocialLoginPopup();
                twPopup.openPopup('<?php echo $block->getLoginUrl()?>', '<?php echo __('Login By Twitter')?>');
            })
        });
    </script>
<?php endif; ?>