<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php
/**
 * Customer additional info for register and login forms
 *
 */
?>
<?php if ($this->helper('Magento\Checkout\Helper\Data')->isContextCheckout()): ?>
    <input name="context" type="hidden" value="checkout" />
<?php endif; ?>
 <!-- <div class="field required">
            <label for="magento_custome" class="label"><span><?php /* @escapeNotVerified */ echo __('Magento custome') ?></span></label>
            <div class="control">
                <input type="text" name="magento_username" id="magento_username" value="<?php //echo $block->escapeHtml($block->getFormData()->getMagentoCustome()) ?>" title="<?php /* @escapeNotVerified */ echo __('Custome') ?>" class="input-text" data-validate="{required:true}">
            </div>
        </div>  -->