

<?php $_order = $block->getOrder() ?>
<div class="admin__table-wrapper">
    <table class="data-table admin__table-primary edit-order-table">
        <thead>
            <tr class="headings">
                <th class="col-product"><span><?php /* @escapeNotVerified */ echo __('Product') ?></span></th>
                <th class="col-status"><span><?php /* @escapeNotVerified */ echo __('Item Status') ?></span></th>
                <th class="col-price-original"><span><?php /* @escapeNotVerified */ echo __('Original Price') ?></span></th>
                <th class="col-price"><span><?php /* @escapeNotVerified */ echo __('Price') ?></span></th>
                <th class="col-ordered-qty"><span><?php /* @escapeNotVerified */ echo __('Qty') ?></span></th>
                <th class="col-subtotal"><span><?php /* @escapeNotVerified */ echo __('Subtotal') ?></span></th>
                <th class="col-tax-amount"><span><?php /* @escapeNotVerified */ echo __('Tax Amount') ?></span></th>
                <th class="col-tax-percent"><span><?php /* @escapeNotVerified */ echo __('Tax Percent') ?></span></th>
                <th class="col-discont"><span><?php /* @escapeNotVerified */ echo __('Discount Amount') ?></span></th>
                <th class="col-total last"><span><?php /* @escapeNotVerified */ echo __('Row Total') ?></span></th>
            </tr>
        </thead>
        <?php 
       $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
 $this->authSession = $objectManager->create('\Magento\Backend\Model\Auth\Session');
 $product = $objectManager->create('\Magento\Catalog\Model\Product');
 $_items=$block->getItemsCollection();

  $email=$this->authSession->getUser()->getEmail();
  $roleName = $this->authSession->getUser()->getRole()->getRoleName();
  $productIds=array();

   //     $_items = $block->getItemsCollection();
      //  print_r($_items->getData());
   //  echo   count($_items); die;
    // print_r($_items->getData());  die;
 ?>
        <?php 

         $i = 0; foreach ($_items as $_item):
         if($roleName=='Supplier'){ 
     
        $sellerEmail=$product->load($_item->getProductId())->getAttributeText('seller_account');
        if($email == $sellerEmail):
            if ($_item->getParentItem()) {
                continue;
            } else {
                $i++;
            } 

        ?>
            <tbody class="<?php /* @escapeNotVerified */ echo $i%2 ? 'even' : 'odd' ?>">
                <?php echo $block->getItemHtml($_item) ?>
                <?php echo $block->getItemExtraInfoHtml($_item) ?>
            </tbody>
     
     <?php   endif;
      } else {
         if ($_item->getParentItem()) {
                continue;
            } else {
                $i++;
            } ?>
            <tbody class="<?php /* @escapeNotVerified */ echo $i%2 ? 'even' : 'odd' ?>">
                <?php echo $block->getItemHtml($_item) ?>
                <?php echo $block->getItemExtraInfoHtml($_item) ?>
            </tbody>
   
   <?php   }  ?>
           
        <?php endforeach; ?>
    </table>
</div>
