
<?php 
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$this->_storeManager =$objectManager->create('\Magento\Store\Model\StoreManagerInterface'); 
$this->_localeCurrency = $objectManager->create("\Magento\Framework\Locale\CurrencyInterface");  

     $productFactory=$objectManager->create("\Magento\Catalog\Model\ProductFactory")->create();
  $currency_code = $this->_storeManager->getStore()->getCurrentCurrencyCode();
$currency_symbol = $this->_localeCurrency->getCurrency($currency_code)->getSymbol();


       
$_order = $block->getOrder();

 $seller_email=$block->getSellerEmail();

 ?>
<?php if ($_order): ?>
    <?php $_items = $_order->getAllItems(); ?>
    <table class="email-items">
        <thead>
            <tr>
                <th class="item-info">
                    <?= /* @escapeNotVerified */  __('Items'); ?>
                </th>
                <th class="item-qty">
                    <?= /* @escapeNotVerified */  __('Qty'); ?>
                </th>
                <th class="item-price">
                    <?= /* @escapeNotVerified */  __('Price'); ?>
                </th>
            </tr>
        </thead>
          
          <?php 
         //  $subtotal=0;
           foreach($_items as $item) : ?>
          <?php 
           $product = $productFactory->load($item->getProductId());
           $sellerAccount=$product->getAttributeText('seller_account');
            if($sellerAccount == $seller_email):
           ?>

          <tr>
                 <td  class="item-info"> <?php  echo  $item->getName(); ?>
                 <p class="sku">SKU : <?php echo $item->getSku(); ?></p> </td>
                 <td class="item-qty"> <?php    echo  $item->getQtyOrdered(); ?></td>
                 <td class="item-price"> <?php  echo  $currency_symbol . $item->getPrice(); ?> </td>
         </tr>
          <?php    //$subtotal+=$item->getPrice();
            endif;
           endforeach;  ?>
           <!-- <tfoot class="order-totals">
            <tr class="subtotal">
            <th colspan="2" scope="row"> <?= /* @escapeNotVerified */  __('Subtotal'); ?></th>
                    <td data-th="Subtotal" style="font-family: 'Open Sans', 'Helvetica Neue', Helvetica, Arial, sans-serif; vertical-align: top; padding: 9px; background-color: #f5f5f5; text-align: right;">
                        <span class="price" style="white-space: nowrap;"><?php //echo $currency_symbol . $subtotal; ?></span>                    </td>
                </tr>
            </tfoot> -->

    </table>
    
    

<?php endif; ?>
