<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var $block \Magento\Catalog\Block\Product\View */
?>
<?php $_product = $block->getProduct(); ?>
<?php $buttonTitle = __('Add to Cart'); ?>
<?php if ($_product->isSaleable()): ?>
<div class="box-tocart">
    <div class="fieldset">
        <?php if ($block->shouldRenderQuantity()): ?>
        <div class="field qty">
            <label class="label" for="qty"><span><?php /* @escapeNotVerified */ echo __('Qty') ?></span></label>
            <div class="control">
                <input type="number"
                       name="qty"
                       id="qty"
                       maxlength="12"
                       value="<?php /* @escapeNotVerified */ echo $block->getProductDefaultQty() * 1 ?>"
                       title="<?php /* @escapeNotVerified */ echo __('Qty') ?>" class="input-text qty"
                       data-validate="<?php echo $block->escapeHtml(json_encode($block->getQuantityValidators())) ?>"
                       />
            </div>
            <div class="qty-changer">
                <a href="javascript:void(0)" class="qty-inc"><i class="porto-icon-up-dir"></i></a>
                <a href="javascript:void(0)" class="qty-dec"><i class="porto-icon-down-dir"></i></a>
            </div>
        </div>
        <?php endif; ?>
        <button class="btn btn-success " type="button" style="height: 40px;color: #fff;">View All Offers</button>
    </div>

<!--check availability-->
 <div class="check-pin">

 <form class="navbar-form navbar-left" role="search" >
    <h4>Check availability at</h4>
     <div class="form-group" >
       <input type="text" class="form-control" placeholder="Enter your Pincode" >
     </div>
  <button type="submit" class="btn btn-default" >Check</button>
   </form>
  </div>


<div class="row vehicle-main">
   <div class="col-md-8 col-sm-8 col-xs-8 col-lg-8">
      <div class="vehicle-check"> 
       <button class="btn btn-warning" type="button">?</button>
         <h4>Will this fit your vehicle</h4>
     </div>
   </div>
   <div class="col-md-4 col-sm-4 col-xs-4 col-lg-4">
    <!--buy now & add to cart-->
         <div class="actions">
            <a  href="#" class="action primary "  id="buynowbutton">
                <span>Buy Now</span>
            </a>
          </div>
        <div class="actions">
            <button type="submit"
                    title="<?php /* @escapeNotVerified */ echo $buttonTitle ?>"
                    class="action primary tocart"
                    id="product-addtocart-button">
                <span><?php /* @escapeNotVerified */ echo $buttonTitle ?></span>
            </button>
            <?php echo $block->getChildHtml('', true) ?>
        </div>

       
   </div>
</div>


    
</div>
<?php endif; ?>
<!-- <div><a href="#" id="buynowbutton"  >click</a></div> -->
<?php if ($block->isRedirectToCartEnabled()) : ?>
<script type="text/x-magento-init">
    {
        "#product_addtocart_form": {
            "Magento_Catalog/product/view/validation": {
                "radioCheckboxClosest": ".nested"
            }
        }
    }
</script>
<?php else : ?>
<script>
    require([
        'jquery',
        'mage/mage',
        'Magento_Catalog/product/view/validation',
        'Magento_Catalog/js/catalog-add-to-cart'
    ], function ($) {
        'use strict';

        $('#product_addtocart_form').mage('validation', {
            radioCheckboxClosest: '.nested',
            submitHandler: function (form) {
                var widget = $(form).catalogAddToCart({
                    bindSubmit: false

                });
         
          widget.catalogAddToCart('submitForm', $(form));
          
        
                return false;
            }
        });

   jQuery( "#buynowbutton" ).click(function(event) {
   jQuery('#product_addtocart_form').trigger('submit');
  
    var interval=setInterval(function () {
       if(jQuery( "#product-addtocart-button" ).hasClass("disabled")==false){
        clearInterval(interval);
           window.location.href="<?php echo $block->getUrl('checkout/cart', ['_secure' => true]);?>";
      
       }
    },2000);
  
});
    });
</script>
<?php endif; ?>



<style>
.check-pin {
 display: inline-block;
}
.check-pin  h4{
 margin: 0; display: inline-block;
}
.check-pin  .form-group {
  margin: 0px;border-radius: 0;border-radius: none;width: 120px;
      display: inline-block;
}
.check-pin  input[type="text"] {
 border-radius: 0px !important;
    height: 30px;
    display: inline-block;
}

.check-pin button {
      color: #fff;
       border: 1px solid #797373;
    background-color: rgb(152,152,152);
    margin: -4px 0px 0 10px;
    border-radius: 0px !important;
    height: 30px;
}
.check-pin .btn-default:hover, .btn-default:focus {
    background-color: #797373;
}
.vehicle-main {
  margin-top: 20px;
}
.vehicle-check {
      border: 1px solid #797373;
    border-radius: 5px;
    display: inline-block;
    padding: 5px;
}

.vehicle-check button {
      display: inline-block;
}
.vehicle-check h4 {
      margin: 0;
    display: inline-block;
}

#buynowbutton {
      text-align: center;
    border: none;
    width: 120px;
    background-color: rgb(255,150,45);
}

#product-addtocart-button {
 border: none;
    /* border: 1px solid #ccc; */
    margin: 10px 0 0 0;
    min-width: 120px;
    widht: 72px;
    padding: 0;
}
</style> 